### ISSUE TITLE
Ability to bypass .gitignore files and generate a minimal file structure

### ISSUE THREAD

**Issue by sir-kokabi** [krivoox/draw-folder-structure#13]
I like your extension and I have two feature suggestions.

Add two extra new items to the right-click menu:

1. Generate Markdown Structure (excluding .gitignored files)
   When the user clicks this item, none of the .gitignored files are generated.
   
2. Generate Minimal Structure.
   When the user clicks this item, repeated file and folder patterns will be minimized. For example, instead of:

MyProject
└── 📁files
    └── file-1.txt
    └── file-2.txt
    └── file-3.txt
    └── file-4.txt
    └── file-5.txt
    └── file-6.txt
    └── file-a.txt
    └── file-b.txt
    └── log.txt
└── 📁files
└── 📁files
└── 📁files
└── 📁utils
└── 📁helpers

It generates this:

MyProject
└── 📁files
    └── file-1.txt
    └── file-2.txt
    └── file-a.txt
    └── file-b.txt
    └── log.txt
└── 📁files
└── 📁utils
└── 📁helpers

This helps me, for example, to illustrate the project structure to AI chatbots using the fewest tokens possible.

**Comment by krivoox** [comment]
Hi friend, thanks for your feedback and sorry for my delay in responding.
I like your suggestions, I will be reviewing them and making some corrections.

Best regards!
