### ISSUE TITLE
doesn't exclude some files

### ISSUE THREAD

**Issue by ilgea** [krivoox/draw-folder-structure#14]
Hello, first of all, thank you for the program you've written. I'd like to talk about a problem I'm experiencing. I hope a solution can be found. I tried to describe my problem below.

   "draw.folder.structure.exclude": [
    "node_modules",
    ".git",
    "dist",
    ".next",
    "out",
    ".ico",
    "manifest.json", --> *st.json
    ".txt", 
    ".gitignore",
    ".md",
    ".png"
  ],

I tried various variations of all these, but it still didn't work. It only excludes when you write the file name completely. Otherwise, it doesn't see it. When you write ".png", it should exclude all png files, when you write "public/.png", it should exclude only png files in the public folder, when you write "logo*.png", it should exclude png files starting with logo. Or it would be great if it works this way.

In addition to all these, I hope you can add a feature that will give an image like the one below. Thank you very much in advance.

![2024-06-13 18 28 02](https://github.com/krivoox/draw-folder-structure/assets/108067475/4065d9ab-55dd-4b4f-ba14-1010fbc8d5a6)

**Comment by indrex** [comment]
Same here. Won't exclude json with either of these:

```
    // Draw folder structure extension
    "draw.folder.structure.exclude": [
        ".json",
        "*.json",
    ],
```

**Comment by krivoox** [comment]
Hi guys! Sorry for the delay and thanks for your feedback!
Currently the extension literally excludes what you write to it, it doesn't look for a .png or any other file extension. But it's a good idea and I'll get to work on it!

Thanks again for the feedback, I will keep you informed of changes from my X account.
