### ISSUE TITLE
exclude doesnt work?

### ISSUE THREAD

**Issue by prodbyeagle** [krivoox/draw-folder-structure#17]
i have these folders in the exclude settings but its still showing the whole .git folder (5000+ lines)

```
  "draw.folder.structure.exclude": [
    "node_modules",
    ".git",
    ".next",
    "out"
  ],
```
![image](https://github.com/user-attachments/assets/e5a745bf-bff4-45a3-a4ea-ff5b2e87cabb)

**Comment by prodbyeagle** [comment]
nvm

**Comment by AlfredoDinunzioTR** [comment]
why do people always do this. submit an issue, then close it with "nvm"  

if it happened to you, then its gonna happen to someone else.
