### ISSUE TITLE
My settings to exclude folders don't work

### ISSUE THREAD

**Issue by benji-stori** [krivoox/draw-folder-structure#18]
- I add the configuration but it does not respect it when generating the structure

<img width="579" alt="Screenshot 2024-09-25 at 5 52 28 p m" src="https://github.com/user-attachments/assets/3038b08f-8d9e-461e-bbda-bcfa0060460c">

<img width="1148" alt="Screenshot 2024-09-25 at 5 53 53 p m" src="https://github.com/user-attachments/assets/f0ab2a6c-6d60-44ad-be81-7642700bd791">

**Comment by krivoox** [comment]
Hey my friend! 
If you are trying to avoid showing the objets folder, delete the last ‘/’ and try again. Like this "**/objects".
If it doesn't work let me know!

**Comment by Hossein-Nodahani** [comment]
If you want to match node_modules directories regardless of depth, you could use a pattern like '**/node_modules'. 
 
 example : 
     "draw.folder.structure.exclude": [
        "**/node_modules",
        "**/.git",
        "**/dist",
        "**/out"
    ]

**Comment by Hossein-Nodahani** [comment]
f you want to match node_modules directories regardless of depth, you could use a pattern like '**/node_modules'
