### ISSUE TITLE
Extension is not ingoing the excluded folders and files. 

### ISSUE THREAD

**Issue by Ajay121code** [krivoox/draw-folder-structure#19]
adding below is not working noting is ignored even after adding this in my setting.json file.

"draw.folder.structure.exclude": [
        "**/node_modules",
        "**/*.git",
        "**/dist",
        "**/*.next",
        "**/out"
    ]
    
    also tried in below format.
    
    "draw.folder.structure.exclude": [
        "/node_modules",
        ".git",
        "/dist",
        ".next",
        "/out"
    ]

**Comment by rrcaddick** [comment]
Adding them like this should work

`  
"draw.folder.structure.exclude": [
    "**/__pycache__", 
    "**/dist", 
    "**/*.log",
    "**/*.tmp", 
    "**/.git", 
    "**/.github",
  ]
`

**Comment by krivoox** [comment]
Hi! As @rrcaddick says try the following:

```
    "draw.folder.structure.exclude": [
        "**/node_modules",
        "**/*.git",
        "**/dist",
        "**/*.next",
        "**/out"
    ],
```
it should work.
You may have an outdated version of the extension.

Greetings 👋

**Comment by jordanlambrecht** [comment]
I can also confirm it's not working with any of these settings:

```
  "draw.folder.structure.exclude": [
    "./.next",
    "./.next/**",
    "**/.next/**",
    "**/.next/*",
    "**/*.next",
    "/.next/",
    ".next",
    ".next/**",
    ".next/*",

    "**/*.git",
    "**/*.git/**",
    ".git",
    ".git/**",
    ".git/*",
    "**/.git/**",
    "**/.git/*",
    "/.git/",

    ".vscode",
    ".vscode/**"
    ".vscode/*",
  ],


However, it does work with `"**/.next",` `    "**/.vscode",`, and `"**/.git",`
